### PR TITLE
First stab at automated comments

### LINKED ISSUE #207: post a comment after building test table
after building the plotly test table, the github API could be used to post a comment to the relevant PR

https://developer.github.com/v3/issues/comments/#create-a-comment

this could save developer time (less copy-pasting test table links), at the risk of overloading PR comments with lots of automatically generated links to the test tables.

### PR DESCRIPTION
**Pull request by cpsievert**
Once completed, this will close #207

### CODE REVIEW

**Comment by cpsievert** [comment]
Why is there is 404? https://travis-ci.org/ropensci/plotly/builds/60056978#L1651

**Comment by cpsievert** [comment]
Must be related to authentication -- https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists

**Comment by cpsievert** [comment]
A few things to fix/think about:

- [ ] Post links to new/different tests?
- [ ] Post comments *after both* builds are finished (is there anyway to tell Travis to do the "pr" build after the "push" build?)

**Comment by cpsievert** [comment]
New test table created at http://ropensci.github.io/plotly-test-table/tables/f4811bf213e8ef3b4686e7db5e23bf8576c44573/index.html

**Comment by cpsievert** [comment]
OK, basic comments are now working ^^^

A couple things left to fix/think about:

- [ ] Post links to new/different tests?
- [ ] Post comments *after both* builds are finished (is there anyway to tell Travis to do the "pr" build after the "push" build?)

**Comment by cpsievert** [comment]
New test table created at http://ropensci.github.io/plotly-test-table/tables/f4811bf213e8ef3b4686e7db5e23bf8576c44573/index.html

**Comment by cpsievert** [comment]
New test table created at http://ropensci.github.io/plotly-test-table/tables/f4811bf213e8ef3b4686e7db5e23bf8576c44573/index.html

**Comment by cpsievert** [comment]
New test table created at http://ropensci.github.io/plotly-test-table/tables/5fba5b6b6813e439505da32880c10c2360ec725d/index.html

**Comment by cpsievert** [comment]
New test table created at http://ropensci.github.io/plotly-test-table/tables/d60157c5a4c287781b7001a2f6a675353a7010c5/index.html

**Comment by cpsievert** [comment]
New test table created at http://ropensci.github.io/plotly-test-table/tables/00c78be43ec6af5576cdb7d2196aafe6286d4215/index.html

**Comment by cpsievert** [comment]
Commit ab1967e94dd17947aae129146bb93ef7203c49ed was successfully merged with fafbff9cffb07a68f6c928024cc43bff83828f2e (master) to create d55e2001c32059f90f963c63db213267c54fe63f. A visual testing table comparing fafbff9cffb07a68f6c928024cc43bff83828f2e with d55e2001c32059f90f963c63db213267c54fe63f 
 http://ropensci.github.io/plotly-test-table/tables/d55e2001c32059f90f963c63db213267c54fe63f/index.html

**Comment by cpsievert** [comment]
Well, this ended up being more work than I anticipated...

Note that the "dev" branch in the testing table should now reflect results *after* merging with master. I think this is a safer/better/right approach (new behavior could sneak in after merging)

@chriddyp @mkcor @tdhock please review and let me know if you have any ideas for other comments/links that you’d like to be automatically posted.

**Comment by mkcor** [comment]
What do you call the "dev" branch? Do you mean the *feature* branch? There is no dev branch in continuous integration (https://github.com/ropensci/plotly/wiki/Development-guidelines#contributors-guide). :baby_chick: 

Reviewing now. Thanks for submitting, @cpsievert

**Comment by cpsievert** [comment]
yea, I meant feature (not dev) branch

**Comment by mkcor** [comment]
Wow, very impressive! :dash: 

Ideally I would like to see these messages as posted by `bot` so it's clearer that they are automated.

Good point on merging with master to see the actual final resulting images.

Regarding the comment, maybe I would prefix it with something like "in the testing environment", otherwise a quick read might seem scary, like "Commit ab1967e was successfully merged into master..." wait, what?

**Comment by cpsievert** [comment]
Thanks @mkcor :blush: 

Good point about the comment, maybe I'll just prefix with "On Travis, ..."?

I agree it'd be nice to have these messages posted by a "bot". Unfortunately, I think that means we'll have to create a new user and grant it write access to this repo...

**Comment by chriddyp** [comment]
wow, pretty sweet!

**Comment by cpsievert** [comment]
Hold on, I might be able to create an organization that can post comments...

**Comment by cpsievert** [comment]
Hmm, it seems as though I'd have to register a web application to post comments via an organization which seems like overkill (not to mention more complicated). I suppose I could create a new user, but someone (Karthik?) would have to grant write access to that user...

**Comment by mkcor** [comment]
@cpsievert It might not be worth the trouble, indeed. Then maybe the comment can start with this line
```
-----BEGIN BOT MESSAGE-----
```
and end with
```
-----END BOT MESSAGE-----
```
to catch our visual attention, and it's no big deal to have it posted by 'you'.

:+1: for "On Travis, ..."

**Comment by cpsievert** [comment]
```---Automatically generated message---```On TravisCI, commit 38a8fb012729db1c5c0e8dc22f104ab1b511f935 was successfully merged with fafbff9cffb07a68f6c928024cc43bff83828f2e (master) to create d1763fcf64b0ce2ce79ac1443d208e1d884382b2. A visual testing table comparing fafbff9cffb07a68f6c928024cc43bff83828f2e with d1763fcf64b0ce2ce79ac1443d208e1d884382b2 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/d1763fcf64b0ce2ce79ac1443d208e1d884382b2/index.html```---Automatically generated message---```

**Comment by cpsievert** [comment]
```---Automatically generated message---``` On TravisCI, commit 581aa0454994aa0b6055a68fbdf92b3ec9d3596b was successfully merged with fafbff9cffb07a68f6c928024cc43bff83828f2e (master) to create ff313ba7849b7302ebfb6ef2ec4340b751e16026. A visual testing table comparing fafbff9cffb07a68f6c928024cc43bff83828f2e with ff313ba7849b7302ebfb6ef2ec4340b751e16026 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/ff313ba7849b7302ebfb6ef2ec4340b751e16026/index.html ```---Automatically generated message---```

**Comment by cpsievert** [comment]
```---Automatically generated message---```
On TravisCI, commit aa50cb00894dabfc5b9d6a056a2361527ed67637 was successfully merged with fafbff9cffb07a68f6c928024cc43bff83828f2e (master) to create 5f50789904853afe1e3f85101389f4c689906f5c. A visual testing table comparing fafbff9cffb07a68f6c928024cc43bff83828f2e with 5f50789904853afe1e3f85101389f4c689906f5c can be found here:
 http://ropensci.github.io/plotly-test-table/tables/5f50789904853afe1e3f85101389f4c689906f5c/index.html
```---Automatically generated message---```

**Comment by cpsievert** [comment]
> The message below was automatically generated 
 On TravisCI, commit 8011a964b65ba66b5e858d2791bcb84024fb52f7 was successfully merged with fafbff9cffb07a68f6c928024cc43bff83828f2e (master) to create 7de5a2853df546467ac5203b053b58d301f9d5e8. A visual testing table comparing fafbff9cffb07a68f6c928024cc43bff83828f2e with 7de5a2853df546467ac5203b053b58d301f9d5e8 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/7de5a2853df546467ac5203b053b58d301f9d5e8/index.html

**Comment by cpsievert** [comment]
> The message below was automatically generated 

 On TravisCI, commit fec97433f0a08ef4ebe8cf3c983c83bf4b870dbf was successfully merged with fafbff9cffb07a68f6c928024cc43bff83828f2e (master) to create 0fb96ef7b29a6053b3a28e2cf3c3907bc75b9762. A visual testing table comparing fafbff9cffb07a68f6c928024cc43bff83828f2e with 0fb96ef7b29a6053b3a28e2cf3c3907bc75b9762 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/0fb96ef7b29a6053b3a28e2cf3c3907bc75b9762/index.html

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/60474246 

 On TravisCI, commit f3b40a7f7844a4863780df5ffb0fe277204059a5 was successfully merged with fafbff9cffb07a68f6c928024cc43bff83828f2e (master) to create df4f3366f07a834ece8d8ace6602d60e6b2584c7. A visual testing table comparing fafbff9cffb07a68f6c928024cc43bff83828f2e with df4f3366f07a834ece8d8ace6602d60e6b2584c7 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/df4f3366f07a834ece8d8ace6602d60e6b2584c7/index.html

**Comment by cpsievert** [comment]
OK, I think I'm happy with the format of the comment now. Feel free to let me know what you think!

**Comment by mkcor** [comment]
Getting really stylish!
All good. :+1:

**Pull request merged**
