### PR TITLE
Carson cookbook density

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/60781024 

 On TravisCI, commit 237b910e16197f12b3005a2a08fa7f3af07d11f1 was successfully merged with d9ecaf43fa75eeef0142cef93361fdd1e936d227 (master) to create 005bdc8aceeacad40e54a3ab75cf93d1d636d73f. A visual testing table comparing d9ecaf43fa75eeef0142cef93361fdd1e936d227 with 005bdc8aceeacad40e54a3ab75cf93d1d636d73f can be found here:
 http://ropensci.github.io/plotly-test-table/tables/005bdc8aceeacad40e54a3ab75cf93d1d636d73f/index.html

**Comment by cpsievert** [comment]
Added some new tests inspired by the "cookbook distributions" tests (note the histogram-fill-factor-identity test identified a bug in the current implementation)

http://ropensci.github.io/plotly-test-table/tables/005bdc8aceeacad40e54a3ab75cf93d1d636d73f/histogram-fill-factor.html
http://ropensci.github.io/plotly-test-table/tables/005bdc8aceeacad40e54a3ab75cf93d1d636d73f/histogram-fill-factor-identity.html
http://ropensci.github.io/plotly-test-table/tables/005bdc8aceeacad40e54a3ab75cf93d1d636d73f/histogram-fill-factor-dodge.html
http://ropensci.github.io/plotly-test-table/tables/005bdc8aceeacad40e54a3ab75cf93d1d636d73f/histogram-fill-factor-facets.html
http://ropensci.github.io/plotly-test-table/tables/005bdc8aceeacad40e54a3ab75cf93d1d636d73f/histogram-vline.html

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/61658206 

 On TravisCI, commit 16df17c1e37918e5571616729b358485a303b09c was successfully merged with 789e1ec11eb939ab9bd054d5384548336aaa0d07 (master) to create 1a8a76a895aa95fd8b81f3dc306b6cbbc9f069ea. A visual testing table comparing 789e1ec11eb939ab9bd054d5384548336aaa0d07 with 1a8a76a895aa95fd8b81f3dc306b6cbbc9f069ea can be found here:
 http://ropensci.github.io/plotly-test-table/tables/1a8a76a895aa95fd8b81f3dc306b6cbbc9f069ea/index.html

**Comment by cpsievert** [comment]
@mkcor @chriddyp ready to merge when you are...

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/63432986 

 On TravisCI, commit b6f4d572e1f03db9b3b5121e1ca5917dacf4369f was successfully merged with c0fb0cf19a7abf7781ea731dd28627a32edb0c83 (master) to create 02f5b345ba03c741d2492cd1320578ec1bb6acc7. A visual testing table comparing c0fb0cf19a7abf7781ea731dd28627a32edb0c83 with 02f5b345ba03c741d2492cd1320578ec1bb6acc7 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/02f5b345ba03c741d2492cd1320578ec1bb6acc7/index.html

**Comment by cpsievert** [comment]
@mkcor @chriddyp ready to merge!

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/64192339 

 On TravisCI, commit 2ea8fe2b511fec3ea11383dfa8f42e98d0876bc2 was successfully merged with fb4049180862004ab55f54198e0187ab9a2b5d71 (master) to create edd66143047f7e93df479cd452bbc8fceae5374b. A visual testing table comparing fb4049180862004ab55f54198e0187ab9a2b5d71 with edd66143047f7e93df479cd452bbc8fceae5374b can be found here:
 http://ropensci.github.io/plotly-test-table/tables/edd66143047f7e93df479cd452bbc8fceae5374b/index.html

**Comment by cpsievert** [comment]
@mkcor @chriddyp ready to merge!

**Comment by chriddyp** [comment]
looks good to me! :dancer:

**Comment by 13bzhang** [comment]
@cpsievert Hi Carson, much better that we've moved the conversation over here. Yes, I updated the version increments. Should I delete your branch now?

**Comment by cpsievert** [comment]
Yep! Branches can always be restored...

**Pull request merged**
