### PR TITLE
Fix #181

### LINKED ISSUE #181: geom_ribbon doesn't respect alpha blending
Consider extending the [ggplot-ribbon](https://github.com/ropensci/plotly/blob/master/tests/testthat/test-ggplot-ribbon.R) test example to include alpha blending:

```r
huron <- data.frame(year=1875:1972, level=as.vector(LakeHuron))
rb <- ggplot(huron, aes(x=year)) + geom_ribbon(aes(ymin=level-1, ymax=level+1), alpha = 0.1)
rb
```

ribbon

Here is the plotly conversion:

rib

I'll look into fixing this in conjunction with adding `geom_smooth`

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by cpsievert** [comment]
@tdhock @chriddyp @mkcor test table looks good to me (let me know if you want an extra test, but I don't think it's necessary)

http://ropensci.github.io/plotly-test-table/tables/5eec8c4a15dc9579ebe0800c9431173847b16feb/index.html

**Comment by tdhock** [comment]
could you please add a test for the functionality that you implemented? That is alpha transparency for the ribbon, right?

**Comment by cpsievert** [comment]
Added this test -- 

<http://ropensci.github.io/plotly-test-table/tables/6a4484d3559254098981aa9174f16c13c709929e/ribbon-alpha.html>

Ready to merge when you are @chriddyp @tdhock

**Comment by chriddyp** [comment]
:+1: looks good to me!

**Pull request merged**
