### PR TITLE
add geo assets so maps render without internet connection

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by cpsievert** [comment]
@chriddyp we'll have to provide an explanation to CRAN as to why we need to include these assets...

```
* checking installed package size ... NOTE
  installed size is  5.5Mb
  sub-directories of 1Mb or more:
    htmlwidgets   5.0Mb
```

**Comment by cpsievert** [comment]
We'll have to wait a couple days to submit to CRAN, but feel free to merge @chriddyp

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/91748513 

 Detected 1 differences -> 

 http://cpsievert.github.io/plotly-test-table/6cd74ba/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/91751780 

 Detected 1 differences -> 

 http://cpsievert.github.io/plotly-test-table/1ac2dc3/scatterplots-jitter

**Comment by chriddyp** [comment]
@cpsievert one issue that I've run into is that the geo assets make the bundle really large (5MB), which for some folks is too big for them to include into their shiny apps or their documents.

`Plotly.plot` will load the geo-assets asynchronously and on-demand (only when a `*geo` plot is made) from the CDN, but of course this requires an internet connection.

Is it possible for us to only load these extra assets with a config or call signature argument? Like `geo_offline=true`?

**Comment by cpsievert** [comment]
Hmm, it is certainly _possible_ but might require a rather ugly hack.

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/97884059 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/4cfcb26/jitter-basic
http://cpsievert.github.io/plotly-test-table/4cfcb26/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/4cfcb26/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/97884059 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/4cfcb26/jitter-basic
http://cpsievert.github.io/plotly-test-table/4cfcb26/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/4cfcb26/scatterplots-jitter

**Comment by cpsievert** [comment]
Closing in favor of #411

**Pull request closed without merging**
