### PR TITLE
Initial CRAN release

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/90434976 

 Detected 1 differences -> 

 http://cpsievert.github.io/plotly-test-table/a426f44/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/90457682 

 Detected 1 differences -> 

 http://cpsievert.github.io/plotly-test-table/05a8c51/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/91345273 

 Detected 1 differences -> 

 http://cpsievert.github.io/plotly-test-table/c7f60fa/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/91367141 

 Detected 10 differences -> 

 http://cpsievert.github.io/plotly-test-table/1d4b81f/plotly-scatterplot
http://cpsievert.github.io/plotly-test-table/1d4b81f/plotly-scatterplot-color-factor
http://cpsievert.github.io/plotly-test-table/1d4b81f/plotly-scatterplot-color-factor-custom
http://cpsievert.github.io/plotly-test-table/1d4b81f/plotly-scatterplot-color-factor-custom2
http://cpsievert.github.io/plotly-test-table/1d4b81f/plotly-scatterplot-color-numeric
http://cpsievert.github.io/plotly-test-table/1d4b81f/plotly-scatterplot-color-numeric-custom
http://cpsievert.github.io/plotly-test-table/1d4b81f/plotly-scatterplot-group
http://cpsievert.github.io/plotly-test-table/1d4b81f/plotly-scatterplot-scatter3d-axes
http://cpsievert.github.io/plotly-test-table/1d4b81f/plotly-scatterplot-symbol
http://cpsievert.github.io/plotly-test-table/1d4b81f/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/91476704 

 Detected 10 differences -> 

 http://cpsievert.github.io/plotly-test-table/cfdb86b/plotly-scatterplot
http://cpsievert.github.io/plotly-test-table/cfdb86b/plotly-scatterplot-color-factor
http://cpsievert.github.io/plotly-test-table/cfdb86b/plotly-scatterplot-color-factor-custom
http://cpsievert.github.io/plotly-test-table/cfdb86b/plotly-scatterplot-color-factor-custom2
http://cpsievert.github.io/plotly-test-table/cfdb86b/plotly-scatterplot-color-numeric
http://cpsievert.github.io/plotly-test-table/cfdb86b/plotly-scatterplot-color-numeric-custom
http://cpsievert.github.io/plotly-test-table/cfdb86b/plotly-scatterplot-group
http://cpsievert.github.io/plotly-test-table/cfdb86b/plotly-scatterplot-scatter3d-axes
http://cpsievert.github.io/plotly-test-table/cfdb86b/plotly-scatterplot-symbol
http://cpsievert.github.io/plotly-test-table/cfdb86b/scatterplots-jitter

**Comment by chriddyp** [comment]
:dancer:

**Pull request merged**
