### PR TITLE
Fix/build

### PR DESCRIPTION
**Pull request by cpsievert**
This would require a major version bump (2.1) since we're changing the default for inheriting properties.

Let me know what you think @chriddyp @cldougl

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/98390637 

 Detected 6 differences -> 

 http://cpsievert.github.io/plotly-test-table/b9613ac/jitter-basic
http://cpsievert.github.io/plotly-test-table/b9613ac/plotly-subplot-group
http://cpsievert.github.io/plotly-test-table/b9613ac/plotly-subplot-simple
http://cpsievert.github.io/plotly-test-table/b9613ac/plotly-subplot-simple2
http://cpsievert.github.io/plotly-test-table/b9613ac/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/b9613ac/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/98391709 

 Detected 6 differences -> 

 http://cpsievert.github.io/plotly-test-table/e173e2b/jitter-basic
http://cpsievert.github.io/plotly-test-table/e173e2b/plotly-subplot-group
http://cpsievert.github.io/plotly-test-table/e173e2b/plotly-subplot-simple
http://cpsievert.github.io/plotly-test-table/e173e2b/plotly-subplot-simple2
http://cpsievert.github.io/plotly-test-table/e173e2b/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/e173e2b/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/98407250 

 Detected 6 differences -> 

 http://cpsievert.github.io/plotly-test-table/36616f1/jitter-basic
http://cpsievert.github.io/plotly-test-table/36616f1/plotly-subplot-group
http://cpsievert.github.io/plotly-test-table/36616f1/plotly-subplot-simple
http://cpsievert.github.io/plotly-test-table/36616f1/plotly-subplot-simple2
http://cpsievert.github.io/plotly-test-table/36616f1/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/36616f1/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/98423556 

 Detected 13 differences -> 

 http://cpsievert.github.io/plotly-test-table/0d6a78e/jitter-basic
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-bar-color-factor-custom
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-scatterplot
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-scatterplot-color-factor
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-scatterplot-color-factor-custom
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-scatterplot-color-factor-custom2
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-scatterplot-color-numeric
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-scatterplot-color-numeric-custom
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-scatterplot-group
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-scatterplot-scatter3d-axes
http://cpsievert.github.io/plotly-test-table/0d6a78e/plotly-scatterplot-symbol
http://cpsievert.github.io/plotly-test-table/0d6a78e/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/0d6a78e/scatterplots-jitter

**Comment by cpsievert** [comment]
I think this is ready to merge @chriddyp @cldougl, but I'll wait for +1 from someone since these are fairly drastic changes.

It's worth noting that `plotly_build()` is idempotent now (building a given plot more than once should be the same as building it once).

You can ignore diffs from the jitter tests above (they're showing up because they use random data -- I still need to fix that). The rest of the diffs look good to me (we don't need a filename for local plots and before we were incorrectly including an additional layout).

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/98589773 

 Detected 13 differences -> 

 http://cpsievert.github.io/plotly-test-table/01f54a3/jitter-basic
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-bar-color-factor-custom
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-scatterplot
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-scatterplot-color-factor
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-scatterplot-color-factor-custom
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-scatterplot-color-factor-custom2
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-scatterplot-color-numeric
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-scatterplot-color-numeric-custom
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-scatterplot-group
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-scatterplot-scatter3d-axes
http://cpsievert.github.io/plotly-test-table/01f54a3/plotly-scatterplot-symbol
http://cpsievert.github.io/plotly-test-table/01f54a3/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/01f54a3/scatterplots-jitter

**Comment by cldougl** [comment]
This all looks good to me (+1 for defaulting to `inherit = FALSE` ) 
:dancer: (as far as I'm concerned)

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/99280220 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/4d27335/jitter-basic
http://cpsievert.github.io/plotly-test-table/4d27335/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/4d27335/scatterplots-jitter

**Pull request merged**
