### PR TITLE
Correcting the order of traces

### PR DESCRIPTION
**Pull request by 13bzhang**
This is a pull request to address #225 "Ordering of traces is wrong". This seems to be a problem with a lot of geoms. I am attempting a general first-cut solution (pretty drastic try) by reversing the order of the traces. I want to see how it fares in the plotly test tables.
@cpsievert @chriddyp

### CODE REVIEW

**Comment by 13bzhang** [comment]
Ok, maybe that is too drastic of a change to reverse the order of the traces since a lot of the tests depend on the order of the traces from the old code. Let me think this over.

**Comment by 13bzhang** [comment]
After realizing how dumb my initial solution was, I decided to reverse the order of the traces only when there is a problem. Right now the two cases where I have detected a problem include:

1. `geom_area`
2. `geom_density` when `position = "stack"`

So I added the [following lines](https://github.com/ropensci/plotly/blob/0448edbe366a111176c54f7516dfff3984fd5e6d/R/trace_generation.R#L279-L287) to `trace_generation.R`:

```r
  # reverse the traces in the following cases:
  # geom_area
  # geom_density with position = stack
  if (g$geom == "area" | 
        g$geom == "density" & l$position$.super$objname == "stack"){
    traces <- rev(traces)
  } else{
    traces
  }
```

I also included tests for the two cases that I list above to `test-ggplot-area.R` and `test-ggplot-density.R`, respectively. I supect there are other cases of these trace orders out of whack. I will keep looking for them. If you find them, let me know.

@cpsievert  @chriddyp

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/65741975 

 On TravisCI, commit 495ba85a436b90f7188996764c0c3f5c11438a34 was successfully merged with 6ff8831c99042d839a67fd0da46c5141d7a12830 (master) to create 5660ddaf3015e927d1c47960946647ad13973176. A visual testing table comparing 6ff8831c99042d839a67fd0da46c5141d7a12830 with 5660ddaf3015e927d1c47960946647ad13973176 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/5660ddaf3015e927d1c47960946647ad13973176/index.html

**Comment by 13bzhang** [comment]
Hit a snag because the dataset for one of the new tests required the package `dplyr`. I rewrote the code so the data gets prepped using base R instead. Good ol' `aggregate`.

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/65745397 

 On TravisCI, commit 6afd57ed4dabbbfde1be0f49bd08dee153edeb47 was successfully merged with 6ff8831c99042d839a67fd0da46c5141d7a12830 (master) to create 2c09c512f388905bc6cb79815db4581e990aa046. A visual testing table comparing 6ff8831c99042d839a67fd0da46c5141d7a12830 with 2c09c512f388905bc6cb79815db4581e990aa046 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/2c09c512f388905bc6cb79815db4581e990aa046/index.html

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/66496333 

 On TravisCI, commit a892b5d120a0b546615e97d30dd2723a7fea3546 was successfully merged with 6ff8831c99042d839a67fd0da46c5141d7a12830 (master) to create e0f0faeaa8a3165b7620956f3d5c903d0bb8e17b. A visual testing table comparing 6ff8831c99042d839a67fd0da46c5141d7a12830 with e0f0faeaa8a3165b7620956f3d5c903d0bb8e17b can be found here:
 http://ropensci.github.io/plotly-test-table/tables/e0f0faeaa8a3165b7620956f3d5c903d0bb8e17b/index.html

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/96085859 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/bdcba39/area-traces_order
http://cpsievert.github.io/plotly-test-table/bdcba39/density-traces_order
http://cpsievert.github.io/plotly-test-table/bdcba39/scatterplots-jitter

**Comment by cpsievert** [comment]
^^^ much better than the test table, huh @chriddyp? :)

(that jitter test is a false positive, just ignore it, I'll fix it later)

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/96121548 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/0696ba9/area-traces_order
http://cpsievert.github.io/plotly-test-table/0696ba9/density-traces_order
http://cpsievert.github.io/plotly-test-table/0696ba9/scatterplots-jitter

**Pull request merged**
