### PR TITLE
API v2

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/207496890 

 Detected 5 differences -> 

 http://cpsievert.github.io/plotly-test-table/d7ffab5/jitter-basic
http://cpsievert.github.io/plotly-test-table/d7ffab5/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/d7ffab5/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/d7ffab5/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/d7ffab5/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/208402487 

 Detected 5 differences -> 

 http://cpsievert.github.io/plotly-test-table/730747d/jitter-basic
http://cpsievert.github.io/plotly-test-table/730747d/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/730747d/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/730747d/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/730747d/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/216894703 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/2b61bfc/cookbook-axes-multiple-abline
http://cpsievert.github.io/plotly-test-table/2b61bfc/heatmap-discrete
http://cpsievert.github.io/plotly-test-table/2b61bfc/heatmap-midpoint
http://cpsievert.github.io/plotly-test-table/2b61bfc/jitter-basic
http://cpsievert.github.io/plotly-test-table/2b61bfc/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/2b61bfc/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/2b61bfc/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/2b61bfc/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/216897468 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/5307a35/cookbook-axes-multiple-abline
http://cpsievert.github.io/plotly-test-table/5307a35/heatmap-discrete
http://cpsievert.github.io/plotly-test-table/5307a35/heatmap-midpoint
http://cpsievert.github.io/plotly-test-table/5307a35/jitter-basic
http://cpsievert.github.io/plotly-test-table/5307a35/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/5307a35/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/5307a35/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/5307a35/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/216946816 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/5fd71c5/cookbook-axes-multiple-abline
http://cpsievert.github.io/plotly-test-table/5fd71c5/heatmap-discrete
http://cpsievert.github.io/plotly-test-table/5fd71c5/heatmap-midpoint
http://cpsievert.github.io/plotly-test-table/5fd71c5/jitter-basic
http://cpsievert.github.io/plotly-test-table/5fd71c5/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/5fd71c5/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/5fd71c5/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/5fd71c5/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/216953026 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/d26d18a/cookbook-axes-multiple-abline
http://cpsievert.github.io/plotly-test-table/d26d18a/heatmap-discrete
http://cpsievert.github.io/plotly-test-table/d26d18a/heatmap-midpoint
http://cpsievert.github.io/plotly-test-table/d26d18a/jitter-basic
http://cpsievert.github.io/plotly-test-table/d26d18a/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/d26d18a/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/d26d18a/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/d26d18a/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/217221839 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/8759e4a/cookbook-axes-multiple-abline
http://cpsievert.github.io/plotly-test-table/8759e4a/heatmap-discrete
http://cpsievert.github.io/plotly-test-table/8759e4a/heatmap-midpoint
http://cpsievert.github.io/plotly-test-table/8759e4a/jitter-basic
http://cpsievert.github.io/plotly-test-table/8759e4a/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/8759e4a/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/8759e4a/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/8759e4a/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/218149169 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/606686f/cookbook-axes-multiple-abline
http://cpsievert.github.io/plotly-test-table/606686f/heatmap-discrete
http://cpsievert.github.io/plotly-test-table/606686f/heatmap-midpoint
http://cpsievert.github.io/plotly-test-table/606686f/jitter-basic
http://cpsievert.github.io/plotly-test-table/606686f/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/606686f/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/606686f/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/606686f/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/219459252 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/3d204c3/cookbook-axes-multiple-abline
http://cpsievert.github.io/plotly-test-table/3d204c3/heatmap-discrete
http://cpsievert.github.io/plotly-test-table/3d204c3/heatmap-midpoint
http://cpsievert.github.io/plotly-test-table/3d204c3/jitter-basic
http://cpsievert.github.io/plotly-test-table/3d204c3/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/3d204c3/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/3d204c3/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/3d204c3/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/220683874 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/52c40b2/cookbook-axes-multiple-abline
http://cpsievert.github.io/plotly-test-table/52c40b2/heatmap-discrete
http://cpsievert.github.io/plotly-test-table/52c40b2/heatmap-midpoint
http://cpsievert.github.io/plotly-test-table/52c40b2/jitter-basic
http://cpsievert.github.io/plotly-test-table/52c40b2/plotly-alpha-blending
http://cpsievert.github.io/plotly-test-table/52c40b2/plotly-subplot-ggmatrix
http://cpsievert.github.io/plotly-test-table/52c40b2/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/52c40b2/scatterplots-jitter

**Comment by cpsievert** [comment]
Oops, didn't mean to do this, and not sure how to remove it, sorry @mkcor 

screen shot 2017-04-18 at 5 48 48 pm

**Comment by mkcor** [comment]
Haha, no worries @cpsievert !  Exciting work, by the way.

**Pull request merged**
