### PR TITLE
Added legends for boxplots and densities

### PR DESCRIPTION
**Pull request by 13bzhang**
This a solution to Issue #212. The legends weren't showing up for boxplots and density plots is because those features were not part of `markLegends` in `ggplotly`. I added them. I also made an except for boxplot so that is takes `markSplit` instead. Finally, I added a test for boxplots where each box-and-whiskers has a different fill. Will add to the existing density plot tests tomorrow to check for legends. 

Now we can enjoy legends:

boxplot_plotly_fixed

density_carson_fixed

@cpsievert @mkcor @chriddyp

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/66186407 

 On TravisCI, commit 6dfa9dad5218dc9c980e9d9d12de6832499bf7a5 was successfully merged with 6ff8831c99042d839a67fd0da46c5141d7a12830 (master) to create b8c2191bacedb8fe7a923215f004a3044b6b831f. A visual testing table comparing 6ff8831c99042d839a67fd0da46c5141d7a12830 with b8c2191bacedb8fe7a923215f004a3044b6b831f can be found here:
 http://ropensci.github.io/plotly-test-table/tables/b8c2191bacedb8fe7a923215f004a3044b6b831f/index.html

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/66186609 

 On TravisCI, commit 6dfa9dad5218dc9c980e9d9d12de6832499bf7a5 was successfully merged with 6ff8831c99042d839a67fd0da46c5141d7a12830 (master) to create b8f6446f92120d6a3d904952dd7374620f6ae6ca. A visual testing table comparing 6ff8831c99042d839a67fd0da46c5141d7a12830 with b8f6446f92120d6a3d904952dd7374620f6ae6ca can be found here:
 http://ropensci.github.io/plotly-test-table/tables/b8f6446f92120d6a3d904952dd7374620f6ae6ca/index.html

**Comment by 13bzhang** [comment]
@cpsievert Hey Carson, do you know my graphs are not showing up the in the test tables?

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/66486075 

 On TravisCI, commit 7b6f87feff32121a2f6503a386d1a0a5c6ea8561 was successfully merged with 6ff8831c99042d839a67fd0da46c5141d7a12830 (master) to create f41f58378bb5c2cfa4f798c0e83c59c49e9ac40e. A visual testing table comparing 6ff8831c99042d839a67fd0da46c5141d7a12830 with f41f58378bb5c2cfa4f798c0e83c59c49e9ac40e can be found here:
 http://ropensci.github.io/plotly-test-table/tables/f41f58378bb5c2cfa4f798c0e83c59c49e9ac40e/index.html

**Comment by cpsievert** [comment]
Ugh, I just spent a couple hours trying to debug. For some reason [the pngs aren't being pushed appropriately](https://github.com/ropensci/plotly-test-table/tree/gh-pages/data/f41f58378bb5c2cfa4f798c0e83c59c49e9ac40e), but not sure why.

The current logic of the test table is super complicated, so if anything goes wrong, it's hard to fix it (this is a big reason why I'm changing the test table infrastructure in #226). I think my time is better spent finishing that new infrastructure.

@mkcor @chriddyp

**Comment by 13bzhang** [comment]
Thanks for checking it out!

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/96356423 

 Detected 42 differences -> 

 http://cpsievert.github.io/plotly-test-table/e078fca/boxplot
http://cpsievert.github.io/plotly-test-table/e078fca/boxplot-datetime
http://cpsievert.github.io/plotly-test-table/e078fca/boxplot-legends_for_fill
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-blank-minor
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-blank-minor-major
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-blank-x
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-blank-y
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-coord-ylim
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-custom-formatter
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-flevels
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-fonts
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-label-funs
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-no-x-title
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-scale.hide
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-scale-name
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-ylim.hide
http://cpsievert.github.io/plotly-test-table/e078fca/density-color
http://cpsievert.github.io/plotly-test-table/e078fca/density-fill
http://cpsievert.github.io/plotly-test-table/e078fca/density-traces_order
http://cpsievert.github.io/plotly-test-table/e078fca/scatterplots-jitter
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-boxes
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-boxes-facet-grid
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-boxes-scales-free
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-boxes-space-free
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-breaks-less
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-breaks-more
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-breaks-nochange
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-discrete-order
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-evenly-spaced-ticks
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-flip
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-hide-ticks-labels
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-hide-ticks-lines-labels
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-hide-y
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-hide-y-keep-grid
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-limits-gap
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-limits-hide
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-scale-labels
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-ycontinuous-ranges
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-ylim-ranges
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-ylim-reversed-ranges
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-yreverse-limits-ranges
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-yreverse-ranges

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/96356423 

 Detected 42 differences -> 

 http://cpsievert.github.io/plotly-test-table/e078fca/boxplot
http://cpsievert.github.io/plotly-test-table/e078fca/boxplot-datetime
http://cpsievert.github.io/plotly-test-table/e078fca/boxplot-legends_for_fill
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-blank-minor
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-blank-minor-major
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-blank-x
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-blank-y
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-coord-ylim
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-custom-formatter
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-flevels
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-fonts
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-label-funs
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-no-x-title
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-scale.hide
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-scale-name
http://cpsievert.github.io/plotly-test-table/e078fca/cookbook-axes-ylim.hide
http://cpsievert.github.io/plotly-test-table/e078fca/density-color
http://cpsievert.github.io/plotly-test-table/e078fca/density-fill
http://cpsievert.github.io/plotly-test-table/e078fca/density-traces_order
http://cpsievert.github.io/plotly-test-table/e078fca/scatterplots-jitter
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-boxes
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-boxes-facet-grid
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-boxes-scales-free
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-boxes-space-free
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-breaks-less
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-breaks-more
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-breaks-nochange
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-discrete-order
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-evenly-spaced-ticks
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-flip
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-hide-ticks-labels
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-hide-ticks-lines-labels
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-hide-y
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-hide-y-keep-grid
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-limits-gap
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-limits-hide
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-scale-labels
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-ycontinuous-ranges
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-ylim-ranges
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-ylim-reversed-ranges
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-yreverse-limits-ranges
http://cpsievert.github.io/plotly-test-table/e078fca/ticks-yreverse-ranges

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/96371066 

 Detected 42 differences -> 

 http://cpsievert.github.io/plotly-test-table/260b9c9/boxplot
http://cpsievert.github.io/plotly-test-table/260b9c9/boxplot-datetime
http://cpsievert.github.io/plotly-test-table/260b9c9/boxplot-legends_for_fill
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-blank-minor
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-blank-minor-major
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-blank-x
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-blank-y
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-coord-ylim
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-custom-formatter
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-flevels
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-fonts
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-label-funs
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-no-x-title
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-scale.hide
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-scale-name
http://cpsievert.github.io/plotly-test-table/260b9c9/cookbook-axes-ylim.hide
http://cpsievert.github.io/plotly-test-table/260b9c9/density-color
http://cpsievert.github.io/plotly-test-table/260b9c9/density-fill
http://cpsievert.github.io/plotly-test-table/260b9c9/density-traces_order
http://cpsievert.github.io/plotly-test-table/260b9c9/scatterplots-jitter
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-boxes
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-boxes-facet-grid
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-boxes-scales-free
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-boxes-space-free
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-breaks-less
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-breaks-more
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-breaks-nochange
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-discrete-order
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-evenly-spaced-ticks
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-flip
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-hide-ticks-labels
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-hide-ticks-lines-labels
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-hide-y
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-hide-y-keep-grid
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-limits-gap
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-limits-hide
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-scale-labels
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-ycontinuous-ranges
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-ylim-ranges
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-ylim-reversed-ranges
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-yreverse-limits-ranges
http://cpsievert.github.io/plotly-test-table/260b9c9/ticks-yreverse-ranges

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/96384466 

 Detected 5 differences -> 

 http://cpsievert.github.io/plotly-test-table/56fda5c/boxplot-legends_for_fill
http://cpsievert.github.io/plotly-test-table/56fda5c/density-color
http://cpsievert.github.io/plotly-test-table/56fda5c/density-fill
http://cpsievert.github.io/plotly-test-table/56fda5c/density-traces_order
http://cpsievert.github.io/plotly-test-table/56fda5c/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/96631939 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/0bcd5bf/boxplot-fillcolor
http://cpsievert.github.io/plotly-test-table/0bcd5bf/boxplot-legends_for_fill
http://cpsievert.github.io/plotly-test-table/0bcd5bf/density-color
http://cpsievert.github.io/plotly-test-table/0bcd5bf/density-fill
http://cpsievert.github.io/plotly-test-table/0bcd5bf/density-traces_order
http://cpsievert.github.io/plotly-test-table/0bcd5bf/jitter-basic
http://cpsievert.github.io/plotly-test-table/0bcd5bf/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/0bcd5bf/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/96635938 

 Detected 8 differences -> 

 http://cpsievert.github.io/plotly-test-table/a9558d5/boxplot-fillcolor
http://cpsievert.github.io/plotly-test-table/a9558d5/boxplot-legends_for_fill
http://cpsievert.github.io/plotly-test-table/a9558d5/density-color
http://cpsievert.github.io/plotly-test-table/a9558d5/density-fill
http://cpsievert.github.io/plotly-test-table/a9558d5/density-traces_order
http://cpsievert.github.io/plotly-test-table/a9558d5/jitter-basic
http://cpsievert.github.io/plotly-test-table/a9558d5/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/a9558d5/scatterplots-jitter

**Pull request merged**
