### PR TITLE
Fixing Legend Name

### PR DESCRIPTION
**Pull request by 13bzhang**
First stab at a solution to Issue #188. Currently, the legend name is the variable name of the fill, color, or shape variable; it has a problem recognizing user generated legend names. I'm trying to fix it so `annotations` takes the user generated legend name when there is one. 

@mkcor @cpsievert @chriddyp

### CODE REVIEW

**Comment by 13bzhang** [comment]
Oops, commits from #235 out sent here for some reason. I will backtrack and re-commit and push.

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/68445728 

 On TravisCI, commit 5158214f270dbc9bbd513e0d252ef44aa7e740b3 was successfully merged with 6ff8831c99042d839a67fd0da46c5141d7a12830 (master) to create f689776326d53eb930477a7b6e104a315ebf56f9. A visual testing table comparing 6ff8831c99042d839a67fd0da46c5141d7a12830 with f689776326d53eb930477a7b6e104a315ebf56f9 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/f689776326d53eb930477a7b6e104a315ebf56f9/index.html

**Comment by 13bzhang** [comment]
@cpsievert Hey Carson, do you know how to extract scale names from a `ggplot` object when people didn't use the `labs` function? 

For instance:

```r
set.seed(3489243)
rho <- round(rnorm(25, 0, 5))
profit <- 0.5 + 0.3 * rho + rnorm(25, 0, 1)
BetaAdjusted <- factor(c(rep(TRUE, 15), rep(FALSE, 10)))
returns.both <- data.frame(rho, profit, BetaAdjusted)
p <- ggplot(aes(x=rho, y=profit,
                color=BetaAdjusted, shape = BetaAdjusted),
            data=returns.both) + 
  geom_point() + scale_shape_discrete(name = "Is Beta Adjusted?")
```

How would I get "Is Beta Adjusted?" out? Is there a universal way to extract the scale name from `ggplot` objects? Or does it differ when people change the `name` in the `scale` part versus when they use `labs`.

**Comment by cpsievert** [comment]
@13bzhang good question, I'm not sure.

**Comment by 13bzhang** [comment]
I'll most something on stacks and see if someone might bait.

**Comment by 13bzhang** [comment]
http://stackoverflow.com/questions/31118785/r-extract-scale-name-from-ggplot-object

Nope guess there's no easy way to do this.

**Comment by cpsievert** [comment]
I posted a solution. Let me know if you have questions.

http://stackoverflow.com/questions/31118785/r-extract-scale-name-from-ggplot-object/31122700#31122700

**Comment by 13bzhang** [comment]
Cool thanks!

**Comment by 13bzhang** [comment]
@cpsievert As you wrote, `ggplot2` might change how `scales` is handled in the future. Right now, do I write code assuming the current `ggplot2` implementation?

**Comment by cpsievert** [comment]
yea, just make to write some tests.

**Comment by 13bzhang** [comment]
@cpsievert I added some more scale types to your function and modified it somewhat. In the case where there are two scales types in the legend, I decided to push combine the legend titles. (This is because Plotly combines the 2 legends into 1 legend.) Should I separate the two titles using a slash (/) or using a comma (,)? 

So for instance from my tests:

```r
set.seed(955)
# Make some noisily increasing data
dat <- data.frame(cond1 = rep(c("A", "B"), each = 10),
                  cond2 = rep(rep(c("C", "D"), each = 5), 2),
                  xvar = 1:20 + rnorm(20, sd = 3),
                  yvar = 1:20 + rnorm(20, sd = 3))
q <- ggplot(dat, aes(x = xvar, y = yvar, color = cond1, shape = cond2)) + 
  geom_point()
```

ggplot2
118_legend_name

Plotly
188_legend_name_plotly

**Comment by cpsievert** [comment]
I merged this into #269, and that will be merged into master in a couple weeks (once the new ggplot2 hits CRAN)

**Pull request merged**
