### PR TITLE
Carson travis hook

### PR DESCRIPTION
**Pull request by cpsievert**
I've been unable to successfully run `make` over at plotly-test-table (see [here](https://github.com/ropensci/plotly-test-table/issues/2) &[here](https://github.com/ropensci/plotly-test-table/issues/5))

Instead of wasting more time trying to debug on different machines, I thought it would be better to automate the job with Travis (as described [here](https://github.com/ropensci/plotly-test-table/issues/4)).

Let me know what you think @tdhock @chriddyp @mkcor

### CODE REVIEW

**Comment by cpsievert** [comment]
This is more complicated than I thought. I'll have to study the ropensci/plotly-test-table code over the next few days to do this properly.

**Comment by tdhock** [comment]
What seems to be the problem?

If I were to describe the travis build script that we need in words, it would be:

- get a copy of the most recently pushed plotly directory, and get its SHA1.
```r
setwd("plotly")
test.SHA1 <- system("git rev-parse HEAD", intern=TRUE)
```
- also checkout master and get its SHA1.
```r
master.SHA1 <- system("git checkout master && git rev-parse HEAD", intern=TRUE)
```
- clone plotly-test-table (into the same directory as the plotly repos), checkout gh-pages.
- create a code_commits.csv with 3 lines
```
user,SHA1,label
ropensci,1d75115f71908261e7e8d30de244f42fbcfa4840,master
ropensci,5c98619896b226be4252bfa8757f2ddb5676f29f,name-of-branch
```
- run make to update table.html and index.html.
- ./add-all-commit-push.sh to push the changes to github.

Is there some way to automatically add a comment with a link to the related PR?

**Comment by chriddyp** [comment]
great idea!

**Comment by cpsievert** [comment]
I'm fairly certain the permission denied error is due to the fact that I don't have write access to ropensci/plotly-test-table. We could either grant me access or someone with write access (@tdhock) could follow the directions in the OAUTH section [here](http://rmflight.github.io/posts/2014/11/travis_ci_gh_pages.html) (and update the .travis.yml file accordingly)

**Comment by cpsievert** [comment]
(in case anyone is curious, I just deleted that API token since it's been compromised by the build log)

**Comment by tdhock** [comment]
I think you should be added to ropensci so you can do it yourself. I asked @karthik if it was possible to add you last week via email, but I haven't heard back yet.

**Comment by cpsievert** [comment]
I have write access to plotly, but not plotly-test-table. I just tried to push to make sure:

```
remote: Permission to ropensci/plotly-test-table.git denied to cpsievert.
fatal: unable to access 'https://github.com/ropensci/plotly-test-table.git/': The requested URL returned error: 403
```

**Comment by tdhock** [comment]
ok i'm pretty sure I just added you as a collaborator so you should be able to write to plotly-test-table now

**Comment by cpsievert** [comment]
Well, this took longer than I'd like to admit, but it seems to be working (and I learned a lot in the process :). Check out the homepage -- http://ropensci.github.io/plotly-test-table/

We should probably think about only keeping/showing the most recent commit for each pull request since we have to clone plotly-test-table for each build. Is that something you'd like to see before merging to master?

Please review and ask me questions @chriddyp @mkcor @tdhock

**Comment by tdhock** [comment]
Wow great work! Thanks Carson. Your Travis skills are amazing! This is exactly what I wanted, and I think it will save us a lot of development and testing time. Also since test tables are now available automatically with every push we will be able to use visual testing much more widely to avoid false negative test results (R CMD check tests that pass but have plots with visually obvious problems).

About "only keeping/showing the most recent commit for each pull request" I don't think it is necessary at this time. We can just look at the test table homepage and pick and choose the links (usually the most recent ones) that we want to copy-paste into PR discussions. And I think it is nice to keep the entire history so then we don't get any broken links in the future.

About those things that you learned in the process, did you write them down somewhere? If so I would like to have a look.

**Comment by cpsievert** [comment]
Thanks Toby! There isn't too much Travis magic beyond what [this post](http://rmflight.github.io/posts/2014/11/travis_ci_gh_pages.html) describes -- I've just made use of a couple more [Travis environments variables](https://github.com/ropensci/plotly/blob/6c05b1b8c2d09359a56426a7f1f1b9c3869d1b53/.push_test_table.sh#L10-11). 

The real struggle here was related to git. If you look at [this build](https://travis-ci.org/ropensci/plotly/builds/52968264), notice how Travis does something like `git clone --depth=50 --branch=carson-travis-hook git://github.com/ropensci/plotly.git ropensci/plotly`. It took me a while, but I eventually realized that I cannot simply fetch/checkout master in this case because of the `--depth=50` option (see [here](https://gist.github.com/cpsievert/698c7f1404f972782e71)). I think this [forces us into a re-clone](https://github.com/ropensci/plotly/blob/6c05b1b8c2d09359a56426a7f1f1b9c3869d1b53/.push_test_table.sh#L20-26) (I could be wrong).

Anyway, if you want to learn more about what is possible, learn from the master --

https://github.com/yihui/knitr/blob/master/.travis.yml#L36-39
https://github.com/yihui/xran

**Comment by cpsievert** [comment]
By the way, Travis recently [announced native R builds](http://blog.travis-ci.com/2015-02-26-test-your-r-applications-on-travis-ci/). I was planning making that switch in a separate pull request, but I could also do that here.

**Comment by tdhock** [comment]
Thanks for the very helpful links.

About the native R builds, @mkcor is on vacation but I'm pretty sure she would say to put it in a separate PR.

Anyway this PR gets my personal +1 but I guess you should wait for +1 from @chriddyp to merge with master.

**Comment by cpsievert** [comment]
Huh, this is weird, any idea why I now get this during `R CMD check`?

```
* checking tests ...

Running ‘testthat.R’ [101s/103s]

ERROR

Running the tests in ‘tests/testthat.R’ failed.

Last 13 lines of output:

4: py$get_figure("get_test_user", 0) at test-plotly-getfigure.R:40

5: stop(resp_header$status)
```

**Comment by chriddyp** [comment]
Hmm... not sure. That command makes a call to Plotly, so if that call failed for some reason (which can happen with timeouts, etc) then it could've failed.. is it possible to re-run the tests with Travis?

**Comment by cpsievert** [comment]
Ah, OK. I won't worry about it then. There is a restart build button on Travis if we ever need it

screen shot 2015-03-04 at 1 49 38 pm


I'm ready to merge when you are @chriddyp

**Comment by tdhock** [comment]
Also that reminds me -- sometimes when I build the plotly-test-table I get blank entries (images that were not produced, since the plotly server returned an error).

This happens pretty much randomly and the only solution I have found is to just re-run the make script.

Thoughts?

**Comment by cpsievert** [comment]
We could do some clever programming, but it'd be easier to just re-start the build. You can get to that trigger above by clicking on 'details' for the relevant 'push' build (the 'pr' build is just to make sure it can be successfully merged with master, but it doesn't run `make` from plotly-test-table)

screen shot 2015-03-04 at 1 56 44 pm

**Comment by chriddyp** [comment]
This is super nice. Now all we need is the rest of the cookbook .R files in the repo and we'll have a pretty amazing test suite! :+1:

**Comment by tdhock** [comment]
I added a reference to this PR in the Dev guildelines https://github.com/ropensci/plotly/wiki/Development-guidelines#visual-test-tables

**Pull request merged**
