### PR TITLE
Smooth transitions

### PR DESCRIPTION
**Pull request by cpsievert**
For some reason, transitions are currently grayed out:

tour

I'm guessing we need to use something akin to `Shiny.addCustomMessageHandler` like [ggvis does](https://github.com/rstudio/ggvis/blob/076e350fa1664f510a2f448e2ee22e67e11f59d6/inst/www/ggvis/js/shiny-ggvis.js#L105-L130) in order for the client to process messages in a logical order

Any experience with this sort of thing @timelyportfolio?

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/122696962 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/a9aac1a/jitter-basic
http://cpsievert.github.io/plotly-test-table/a9aac1a/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/a9aac1a/scatterplots-jitter

**Comment by cpsievert** [comment]
FWIW, the graying out isn't an issue when the duration is 0, but it'd be nice to avoid the graying out for any duration level:

tour

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/122703398 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/c4767ee/jitter-basic
http://cpsievert.github.io/plotly-test-table/c4767ee/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/c4767ee/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/122717671 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/bba831b/jitter-basic
http://cpsievert.github.io/plotly-test-table/bba831b/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/bba831b/scatterplots-jitter

**Comment by timelyportfolio** [comment]
I really like this concept, but I think pursuing this on the `R` side might be dangerous long-term.  Has there been any discussion on the JavaScript side to handle transitions in any of the `re-` Plotly functions?

**Comment by cpsievert** [comment]
I agree. This is mostly for my own use/education. I also hope it provides some motivation to provide some more officical support in plotly.js. Here is the only issue I can find on the matter https://github.com/plotly/plotly.js/issues/142

I really like the way Vega approaches this https://github.com/vega/vega/wiki/Streaming-Data

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/122717671 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/bba831b/jitter-basic
http://cpsievert.github.io/plotly-test-table/bba831b/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/bba831b/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/123812169 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/d148bf8/jitter-basic
http://cpsievert.github.io/plotly-test-table/d148bf8/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/d148bf8/scatterplots-jitter

**Comment by cpsievert** [comment]
This probably won't see the light of day since plotly.js will likely be developing an `.animate()` method -- https://github.com/plotly/plotly.js/pull/550

Nevertheless, if might be useful to come back to some of these ideas...

**Comment by cpsievert** [comment]
Closing as plotly.js now has an animate method -- http://rickyreusser.com/animation-experiments/

**Pull request closed without merging**
