### PR TITLE
Removed Slack notifications

### PR DESCRIPTION
**Pull request by karthik**
Hi Plotly team,
I removed a couple of lines from the `.travis.yml` because the notifications to our slack build room are a bit overwhelming at the moment. Since @sckott and I are not actively helping with this package right now, these notifications don't help us much (and also masks the others). This PR just removes that notification. But as always, you can ping us anytime for any help.

Thanks,
- Karthik

### CODE REVIEW

**Comment by cpsievert** [comment]
I was just pinged by @sckott on Twitter about removing Slack notifications. Feel to merge this @mkcor @chriddyp

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/63685320 

 On TravisCI, commit 7d443aa314244e7a48581d96d9930f1dcb4e204c was successfully merged with edf055bc51a85f72d30a261115adfeff3d8ce4d3 (master) to create 73070a8c401de4fd6f1a8f44a4cf0feb4e6c1ce6. A visual testing table comparing edf055bc51a85f72d30a261115adfeff3d8ce4d3 with 73070a8c401de4fd6f1a8f44a4cf0feb4e6c1ce6 can be found here:
 http://ropensci.github.io/plotly-test-table/tables/73070a8c401de4fd6f1a8f44a4cf0feb4e6c1ce6/index.html

**Comment by mkcor** [comment]
@cpsievert Just a question: Why did you merge in branch `carson-bar` and not `master`?

**Comment by cpsievert** [comment]
Oops, my mistake. I think the HEAD is the same so I don't think it will
make a difference. Feel free to just push a commit to master that removes
these lines since that'd be cleanest

**Comment by mkcor** [comment]
All right.  Done (via 0e91034604a3fd38f2b78308).

**Pull request closed without merging**
