### PR TITLE
Speed up group2NA via data.table

### PR DESCRIPTION
**Pull request by cpsievert**
Branched off of #996

### CODE REVIEW

**Comment by cpsievert** [comment]
@msummersgill I'm very close to #996 in terms of the [final benchmark](https://github.com/ropensci/plotly/pull/996#issuecomment-301185120)

screen shot 2017-05-23 at 1 50 25 pm


Is there anything you'd like to see done differently? Tests are passing and I'm happy with the speed improvement

**Comment by cpsievert** [comment]
@msummersgill I'm very close to #996 in terms of the [final benchmark](https://github.com/ropensci/plotly/pull/996#issuecomment-301185120)


screen shot 2017-05-23 at 2 35 38 pm


Is there anything you'd like to see done differently? Tests are passing and I'm happy with the speed improvement

**Comment by msummersgill** [comment]
Carson- I'm traveling for the next week without a keyboarded computer, so I'm having a somewhat challenging time reviewing this in detail. Is there a time window you're looking at for the next version release? If I can look into it next week, I'd love to review in further detail, but if the speed-up you're seeing with this PR will make a big difference that you want to implement sooner, I'd trust your evaluation and I can always look at some of the optimization side of things to tweak on a later release if necessary. Either way, if this PR is roughly on par with the speed I was seeing then RStudio/web browser capabilities are the biggest issue at hand anyway.

**Comment by cpsievert** [comment]
No worries, I'm hoping to get this into the next CRAN release (in the next few days).

Feel free to revisit and send me PR(s) as you see fit -- thank you very much for prompting me to do this!

**Pull request merged**
