### PR TITLE
Toby legend hiding

### PR DESCRIPTION
**Pull request by tdhock**
This fixes "legend doesn't hide" from #161

### CODE REVIEW

**Comment by tdhock** [comment]
The updated test table

http://ropensci.github.io/plotly-test-table/tables/0aba7b1b01dd50c43124b5ffbc0840310cae50ef/index.html

shows that legends are hidden

http://ropensci.github.io/plotly-test-table/tables/0aba7b1b01dd50c43124b5ffbc0840310cae50ef/bar-aes-fill-guides-fill-none.html

and that we can now render the color aesthetic for bar plots

http://ropensci.github.io/plotly-test-table/tables/0aba7b1b01dd50c43124b5ffbc0840310cae50ef/bar-aes-colour-guides-fill-FALSE.html

**Comment by tdhock** [comment]
@chriddyp @cpsievert @mkcor please code review

**Comment by chriddyp** [comment]
Cool! Do we have any tests for "partially" hidden legends? In Plotly, you can hide traces from the legend on the per-trace level with `showlegend` (https://plot.ly/r/reference/#scatter-showlegend). This functionality looks good (:+1:) , but it might be worth putting in a partially hidden legend test just so that we're aware of the behavior and possible regressions. A couple searches: http://stackoverflow.com/questions/15704934/remove-certain-legend-variables-and-legend-values-from-ggplot2, http://stackoverflow.com/questions/14604435/turning-off-some-legends-in-a-ggplot

**Comment by tdhock** [comment]
I added some tests for partially hidden legends in

https://github.com/ropensci/plotly/blob/toby-legend-hiding/tests/testthat/test-ggplot-legend.R

**Comment by chriddyp** [comment]
cool, looks good!

**Comment by tdhock** [comment]
To my eyes the test table shows no regressions

http://ropensci.github.io/plotly-test-table/tables/b178933934c57ba8a5efda61dd4ba3e537b6f2eb/index.html

and in fact it shows that we can now support some kinds of legend breaks that master does not support at this time

http://ropensci.github.io/plotly-test-table/tables/b178933934c57ba8a5efda61dd4ba3e537b6f2eb/legend-iris-trace-showlegend-FALSE.html

http://ropensci.github.io/plotly-test-table/tables/b178933934c57ba8a5efda61dd4ba3e537b6f2eb/legend-iris-2traces-showlegend-FALSE.html

**Comment by chriddyp** [comment]
:+1: - looks good!

**Pull request merged**
