### PR TITLE
add to_basic methods for GeomCrossbar, GeomQuantile, GeomRug, GeomSpoke

### PR DESCRIPTION
**Pull request by sctyner**
I hope these are useful!

### CODE REVIEW

**Comment by cpsievert** [comment]
omg, you are the best @sctyner!

**Comment by sctyner** [comment]
Haha @cpsievert thanks! Let me know if you need examples or anything. :)

**Comment by cpsievert** [comment]
If you are willing, a few simple tests would be great! To be honest, most of our "legacy" ggplot2 tests are confusing, hard to read, and I'm hoping to overhaul them someday so they are more understandable to newcomers. A test sort of like this for each geom, though, would be awesome -- https://github.com/ropensci/plotly/blob/master/tests/testthat/test-animate-highlight.R#L131-L143

Also, the more `aes()` combinations we can test, the better, and also please follow a file naming strategy like this -- https://github.com/ropensci/plotly/blob/master/tests/testthat/test-ggplot-histogram.R

**Comment by sctyner** [comment]
I can do that. It should be good practice for me for testing my own packages! I'll keep you posted.

**Comment by cpsievert** [comment]
Awesome, and don't worry about the travis build currently failing -- something is wrong with the pull request build. As long as you can run `load_all(); source("tests/testthat.R", chdir = T)` locally, and all the tests pass, we should be good!

**Comment by cpsievert** [comment]
@sctyner could you add me as a collaborator on your fork of plotly (under settings)? That will make it easier for me to push commits to your pull request

**Comment by cpsievert** [comment]
@sctyner do you know what all this notch business inside `GeomCrossbar$draw_panel` is about

**Comment by sctyner** [comment]
@cpsievert Done! And as far as the notch business, no clue. I imagine that will need to be accommodated for in the to_basic method. If I figure it out, I'll let you know!

**Comment by cpsievert** [comment]
ok, I'm super excited to merge, so I'm gonna pull the trigger without tests, but feel free to start a new pull request with tests (or more geoms :)!

**Pull request merged**
