### PR TITLE
Copy extras over from plotly.js, if necessary

### PR DESCRIPTION
**Pull request by cpsievert**
This addresses #375 and #356 by leveraging a new environment variable which should point to the plotly.js source. In other words, you can render MathJax and/or maps without an internet connection by doing something like:

``` shell
git clone https://github.com/plotly/plotly.js.git
cd plotly.js
export plotly_jsdir=`pwd`
echo "Sys.setenv('plotly_jsdir', '$plotly_jsdir')" >> ~/.Rprofile
```

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/103455036 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/21067bc/jitter-basic
http://cpsievert.github.io/plotly-test-table/21067bc/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/21067bc/scatterplots-jitter

**Comment by cpsievert** [comment]
MathJax isn't quite working yet as you can see here -- http://cpsievert.github.io/widgetHub/

**Comment by cpsievert** [comment]
TODO: why does this warning occur?

```r
> plot_ly()
Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former
```

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/103694301 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/dd886f8/jitter-basic
http://cpsievert.github.io/plotly-test-table/dd886f8/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/dd886f8/scatterplots-jitter

**Comment by cpsievert** [comment]
Also, [injecting `<script>` to load mathjax via CDN isn't working](https://github.com/ropensci/plotly/blob/a7d61b261aaaa5126538ef2df16c054b979cb2b1/inst/htmlwidgets/plotly.js#L22-L28), and I don't think their a nice way to declare a non-local dependency with htmltools/htmlwidgets （╯°□°）╯ ┻━┻

**Comment by timelyportfolio** [comment]
I am not sure of precedent here with other packages, so I will look for other examples of similar functionality.  There is this script in `rmarkdown` to prune `MathJax` to a smaller size.  Here are a couple of poorly named functions to download the additional assets from Plotly for maps and MathJax to start the discussion/iteration.  Then we will need some add dependency functions to add the assets to the Plotly htmlwidget.  We have the option to do either local or web assets in these added dependencies.

```
plotly_download_map_dep <- function(){
  # find location of htmlwidgets assets in plotly package
  plotly_dir <- system.file("htmlwidgets/lib",package="plotly")
  
  # check to see if directory already exists
  exists_map_dir <- 'plotlymaps' %in% basename(plotly_dir)
  
  maps_dir <- file.path(plotly_dir,"plotlymaps")
  
  if(!exists_map_dir){
    dir.create(maps_dir)
  }
  download.file(
    url = "https://cdn.rawgit.com/plotly/plotly.js/master/dist/plotly-geo-assets.js",
    destfile = file.path(maps_dir,"plotly-geo-assets.js")
  )
  return(file.path(maps_dir,"plotly-geo-assets.js"))
}
```

**Comment by cpsievert** [comment]
Thanks @timelyportfolio. I think I'd prefer to grab assets from the relevant plotly.js release via GitHub's API, sort of like the `inst/plotlyjs.R` script

**Comment by timelyportfolio** [comment]
@cpsievert, can you explain why?  This would require downloading the whole repo for a couple of files.

**Comment by cpsievert** [comment]
True, I'm mainly concerned about versioning of the assets. As @chriddyp mentions [here](https://github.com/ropensci/plotly/pull/302#issuecomment-157763691), maybe we could grab the assets from our CDN (and hopefully those are versioned)?

**Comment by timelyportfolio** [comment]
I was looking for the cdn location.  Thanks for the pointer.  Probably better to use that.

**Comment by fabiangehring** [comment]
I didn't follow the discussion in the different issues about making geo plots available...

But if size is an issue, why not offering the offline content in another package like "plotlyOffline", comparable to "shinythemes" and "shiny". Plotly could then stay the same and gaining an "asset"-config with values "auto", "offline" or "online". Auto could check if the required assets are available and use them if yes and download otherwise. Different asset versions could be managed like normal package version dependencies. 

I think this would keep plotly small but available "offline" if necessary. And As far as I can tell the implementation shouldn't be too difficult?

**Comment by danielsjf** [comment]
What is the current status of this development? I like the idea of @fabiangehring as this practice is indeed used for many other R packages. The usage of online VS offline could be handled with an argument in the function or an option.

Specifically for the use case of #302, it is annoying that the maps are not shown in Rstudio. This has been an issue since late 2015.

**Comment by cpsievert** [comment]
@danielsjf at this point, I would like have to rethink this PR and probably create a helper package, say `plotlyDependencies`, which would bundle and automatically infer which (minimal amount) of [plotly assets](https://github.com/plotly/plotly.js/tree/master/dist) are needed for rendering.

Unfortunately, at the moment, we don't fund have the time/funding. [Please get in touch](https://plot.ly/products/consulting-and-oem/) if you're interesting it supporting

**Comment by cpsievert** [comment]
Closing in favor of #1283

**Comment by eddy-ojb** [comment]
@cpsievert @chriddyp Did this get solved? I am running plotly Dash on an offline server and struggling to get the geo assets to load for maps. Specifically, Plotly is looking for assets like https://cdn.plot.ly/usa_110m.json. Is there a new method to render this locally?

**Pull request closed without merging**
