### PR TITLE
Include license text in LICENSE file

### PR DESCRIPTION
**Pull request by mkcor**
Reference: http://opensource.org/licenses/MIT

/cc @tdhock @chriddyp

### CODE REVIEW

**Comment by cpsievert** [comment]
@mkcor `MIT + file LICENSE` is the format that CRAN prefers. See http://r-pkgs.had.co.nz/description.html#license

**Comment by mkcor** [comment]
@cpsievert Thanks! Oh, I didn't look into R culture, I have to admit. I wanted to make things more standard/clear following comments by @tdhock but it looks like our current license info already complies with the CRAN standard... So maybe I should just close this PR. Sorry for the noise.
Toby, what do you say?

**Comment by cpsievert** [comment]
No problem @mkcor, it's a silly convention. BTW, is the goal to submit to CRAN? The NOTEs/WARNINGs I see from R CMD check look fixable. The one potential problem is the use of `ggplot2:::plot_theme`, but we could just copy/paste avoid CRAN yelling at us...

**Comment by mkcor** [comment]
@cpsievert Short term, not really.  But you are right, it shouldn't be too much work.  There's also the `IRdisplay` dependency.

**Pull request closed without merging**
