### PR TITLE
WIP: parallelize travis tests with test matrix

### PR DESCRIPTION
**Pull request by chriddyp**

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/75292645 



On TravisCI, commit 4eea809 was successfully merged with a97299c (master) to create 13b67f1. A visual testing table comparing a97299c with 13b67f1 can be found here -> 

 http://cpsievert.github.io/plotly-test-table/R/13b67f1/

Detected 0 differences

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/75306751 



On TravisCI, commit a968521 was successfully merged with a97299c (master) to create ac2a030. A visual testing table comparing a97299c with ac2a030 can be found here -> 

 http://cpsievert.github.io/plotly-test-table/R/ac2a030/

Detected 0 differences

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/75310706 



On TravisCI, commit 8a16c03 was successfully merged with a97299c (master) to create 194993b. A visual testing table comparing a97299c with 194993b can be found here -> 

 http://cpsievert.github.io/plotly-test-table/R/194993b/

Detected 0 differences

**Comment by cpsievert** [comment]
Splitting up tests across builds won't work with the current infrastructure. The reason is that we need access to _all_ of the figures to build the test table, but each test runs independently of one another (and, at least currently, each build tries to build and push the test table). 

There might be some way to run build-push-comment.R after _all_ the builds have passed, but it seems like it might not be possible using travis alone since (I don't think) there is a centralized file system across the builds.

**Comment by chriddyp** [comment]
yeah, and it looks like travis doesn't completely parallelize the builds, only does 5 at a time :(

**Pull request closed without merging**
