### PR TITLE
fix and speed up master tests

### PR DESCRIPTION
**Pull request by chriddyp**

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/75208662 



On TravisCI, commit 1a53bc6 was successfully merged with a97299c (master) to create f886940. A visual testing table comparing a97299c with f886940 can be found here -> 

 http://cpsievert.github.io/plotly-test-table/R/f886940/

Detected 0 differences

**Comment by chriddyp** [comment]
hey @cpsievert - a new test user fixes and speeds up the tests (you were right!). I added a filename argument to the test script to prevent the proliferation of plots for the ongoing tests. I don't *think* that this will affect the test tables since we just download the images locally, but wanted to double check before I merge

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/75302861 



On TravisCI, commit 5befc5b was successfully merged with a97299c (master) to create 76936fc. A visual testing table comparing a97299c with 76936fc can be found here -> 

 http://cpsievert.github.io/plotly-test-table/R/76936fc/

Detected 0 differences

**Comment by cpsievert** [comment]
Thanks @chriddyp! Assuming all goes well with this build feel free to merge!

**Pull request merged**
