### PR TITLE
Send 'plotly_click' and 'plotly_selected' events to shiny when in shinyMode

### PR DESCRIPTION
**Pull request by cpsievert**
@chriddyp @jp @cldougl

I talked to @jcheng5 today. He suggested that we don't yet rely on crosstalk, as it's still very experimental, and may never be officially supported.

Later I realized that, in #312, crosstalk is only used to send plotly event data to the shiny server. It turns out that isn't super hard to implement using shiny alone, so I've done that here.

[Here](http://104.131.111.111:3838/plotlyEvents/) is a barebones example ([source](https://github.com/ropensci/plotly/blob/feature/transmit/inst/examples/events/app.R))

To see how the interface for accessing plotly user event data has changed for those older examples, see https://github.com/cpsievert/shiny_apps/commit/5633b6ebca4e8f4e141b405d5fec2cc5a011a8c8 (ignore the inline stuff, cc @pssguy)

A few things left to sort through:
  1. In the basic example above, notice that if you select point(s), then double click to unselect, the selection doesn't clear in the linked views. @etpinard, if possible, a 'plotly_doubleClick' event would be a _huge_ help here!
  2. Do we want to support 'plotly_hover'? If so, that probably means we should clear the selection on 'plotly_unhover', but I imagine this quickly leads to glitchy behavior when hovering over a bunch of points.
  3. Should we provide an option to _not_ send plotly user selections to shiny?

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/103754167 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/ac37699/jitter-basic
http://cpsievert.github.io/plotly-test-table/ac37699/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/ac37699/scatterplots-jitter

**Comment by jackparmer** [comment]
Nice! ^^^ ping @alexcjohnson re "plotly_doubleClick" event

**Comment by etpinard** [comment]
@cpsievert adding a doubleclick emitter would be a 2-line patch.

The only thing we need to discuss, is what the `eventData` should be on doubleclick?

The same as the old selection, an empty object, or something else?

**Comment by cpsievert** [comment]
@etpinard I don't think I have a preference for `eventData` as I'll probably send `null` regardless

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/103883249 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/b335f05/jitter-basic
http://cpsievert.github.io/plotly-test-table/b335f05/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/b335f05/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/103891945 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/e5a4181/jitter-basic
http://cpsievert.github.io/plotly-test-table/e5a4181/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/e5a4181/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/103891945 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/e5a4181/jitter-basic
http://cpsievert.github.io/plotly-test-table/e5a4181/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/e5a4181/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/104151969 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/7646e61/jitter-basic
http://cpsievert.github.io/plotly-test-table/7646e61/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/7646e61/scatterplots-jitter

**Comment by Vestaxis** [comment]
+1 from me too for plotly_doubleClick. Would be really great to have. Only reason why I'm occasionally using ggplot in Shiny apps.

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/106518970 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/9b58b5b/jitter-basic
http://cpsievert.github.io/plotly-test-table/9b58b5b/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/9b58b5b/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/108431033 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/ff1cf39/jitter-basic
http://cpsievert.github.io/plotly-test-table/ff1cf39/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/ff1cf39/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/108431033 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/ff1cf39/jitter-basic
http://cpsievert.github.io/plotly-test-table/ff1cf39/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/ff1cf39/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/109775749 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/1f3207a/jitter-basic
http://cpsievert.github.io/plotly-test-table/1f3207a/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/1f3207a/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/109786860 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/59f6953/jitter-basic
http://cpsievert.github.io/plotly-test-table/59f6953/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/59f6953/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/111644325 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/26589eb/jitter-basic
http://cpsievert.github.io/plotly-test-table/26589eb/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/26589eb/scatterplots-jitter

**Comment by jackparmer** [comment]
Hey @cpsievert , is it still possible to get `plotly_hover` and `plotly_unhover` in here? The folks over at climate corporation asked for it a few weeks ago, and I forgot about this PR being open.
(/cc @royr2 @charleyferrari )

**Comment by jackparmer** [comment]
A few folks are already trying to hack access to the hover events:
http://bl.ocks.org/ramnathv/dd524aa6ce9d90fc80cf
http://stackoverflow.com/questions/34031570/mouseover-in-plotly-and-shiny

**Comment by cldougl** [comment]
Nice!!!

**Comment by jackparmer** [comment]
:tada: :tada: :tada:

**Comment by tmhdunn** [comment]
Is there any possibility of getting plotly click event data for the white space? Would be useful inmaking something where the user can click to add data points.

**Pull request merged**
