### PR TITLE
add inline argument to plotlyOutput()

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/101719093 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/18e3468/jitter-basic
http://cpsievert.github.io/plotly-test-table/18e3468/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/18e3468/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/101719263 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/e1aac3b/jitter-basic
http://cpsievert.github.io/plotly-test-table/e1aac3b/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/e1aac3b/scatterplots-jitter

**Comment by cpsievert** [comment]
> The message below was automatically generated after build https://travis-ci.org/ropensci/plotly/builds/101719404 

 Detected 3 differences -> 

 http://cpsievert.github.io/plotly-test-table/66b6ac4/jitter-basic
http://cpsievert.github.io/plotly-test-table/66b6ac4/scatterplots-geom_jitter
http://cpsievert.github.io/plotly-test-table/66b6ac4/scatterplots-jitter

**Comment by justin-y** [comment]
Hi, any update on this being added to the package? 

Thanks!

**Pull request merged**
