### PR TITLE
Carson ribbon

### PR DESCRIPTION
**Pull request by cpsievert**
This pull request re-implements ribbon as a basic polygon (in a similar fashion to [rect](https://github.com/ropensci/plotly/pull/178)).

One major benefit of doing so is that `geom_ribbon()` (and consequently `geom_smooth()`)  will respect fill/colour/group aesthetics.

### CODE REVIEW

**Comment by cpsievert** [comment]
It's worth noting that I haven't (yet) added the invisible errorbars ([as suggested by Toby](https://github.com/ropensci/plotly/issues/190#issuecomment-83040426)) to aid comparison of upper and lower bounds of ribbons upon hover. If there are multiple groups, that could get quite busy, so my suggestion would be to only draw the invisible errorbars when there is 1 group. Does anyone object to that idea? If not, I'll likely implement that in a separate pull request.

**Comment by cpsievert** [comment]
Note the new tests --

http://ropensci.github.io/plotly-test-table/tables/39b254657b53c4d5fba34d07c6dde38db64c3ded/ribbon-group.html

http://ropensci.github.io/plotly-test-table/tables/39b254657b53c4d5fba34d07c6dde38db64c3ded/ribbon-colour.html

http://ropensci.github.io/plotly-test-table/tables/39b254657b53c4d5fba34d07c6dde38db64c3ded/ribbon-fill.html

http://ropensci.github.io/plotly-test-table/tables/39b254657b53c4d5fba34d07c6dde38db64c3ded/smooth-group.html

http://ropensci.github.io/plotly-test-table/tables/39b254657b53c4d5fba34d07c6dde38db64c3ded/smooth-colour.html

http://ropensci.github.io/plotly-test-table/tables/39b254657b53c4d5fba34d07c6dde38db64c3ded/smooth-fill.html

The smoother legends still need a bit of work...hopefully I can fix that tomorrow.

**Comment by tdhock** [comment]
looks good to me. did you add any tests for ribbons and facets?

**Comment by cpsievert** [comment]
No, but good idea. Do you think I should put them in a separate test file?

**Comment by tdhock** [comment]
same file is fine with me.

**Comment by cpsievert** [comment]
Here is a test for facetted smooths -- 

http://ropensci.github.io/plotly-test-table/tables/aaf302ed8f9fb55b52f90b156425cb9f1124f52e/smooth-facet.html

Unfortunately [my attempt](https://github.com/ropensci/plotly/commit/b50a96952d482c3322a235928970cb424c986ed1) to avoid redundant legend entries breaks this plot in a weird way (I'm not sure why) -- 

http://ropensci.github.io/plotly-test-table/tables/154b7790508a5da192297f191a10e2c94fb337f7/path-line-symbols.html

Does anyone have any other thoughts/opinions on how to best avoid redundant legend entries?

**Comment by cpsievert** [comment]
The test table looks good to me. Ready to merge when you are @tdhock @chriddyp @mkcor 

http://ropensci.github.io/plotly-test-table/tables/2e26cc0e393426fd66c5ae47440c4e1657c343ec/index.html

**Comment by tdhock** [comment]
this plot still has multiple legend entries ... can you add a test for that? and then fix it?

http://ropensci.github.io/plotly-test-table/tables/2e26cc0e393426fd66c5ae47440c4e1657c343ec/smooth-facet.html

**Comment by cpsievert** [comment]
At first I was thinking that was the correct behavior since the legend entries have different alpha levels; however, the more I think about it, in most cases, the differences in alpha should be ignored (especially if the entry names are the same). Anyway, I go ahead and make sure this becomes one legend.

**Comment by cpsievert** [comment]
OK, legend entry comparison will now ignore the alpha level, so we get the desired result here -- 

http://ropensci.github.io/plotly-test-table/tables/a13e92794153452ae16252c6799dba7983462aae/smooth-facet.html

The rest of the table looks good to me. Go ahead and merge when ready @tdhock @chriddyp @mkcor 

http://ropensci.github.io/plotly-test-table/tables/a13e92794153452ae16252c6799dba7983462aae/

**Comment by chriddyp** [comment]
hey sorry just checking in on this. I don't understand why fill/colour/group can't be done with multiple traces and fill?

**Comment by chriddyp** [comment]
is it possible to see the json or url for this test? http://ropensci.github.io/plotly-test-table/tables/a13e92794153452ae16252c6799dba7983462aae/smooth-fill2.html
image

is the fill a polygon or a trace?

**Comment by tdhock** [comment]
when we make the test table we write a log file for every download attempt https://github.com/ropensci/plotly-test-table/blob/gh-pages/table.R#L250 

for your example there is supposed to be this log file http://ropensci.github.io/plotly-test-table/data/a13e92794153452ae16252c6799dba7983462aae/smooth-fill2.log which should contain the plotly URL

but it is not found. why are logs not getting pushed to the plotly-test-table repos?

**Comment by cpsievert** [comment]
The test table is slightly broken right now, so let's postpone this until that's fixed. Follow the discussion [here](https://github.com/ropensci/plotly-test-table/issues/7)

**Comment by tdhock** [comment]
i fixed the bugs and re-built the test table, voilà

http://ropensci.github.io/plotly-test-table/tables/ef301b0e7c602b1cb1484f73426ac30dcbf24983/big.html

**Comment by cpsievert** [comment]
Nice! Thanks @tdhock! 

I merged that pull request which makes logs available, so @chriddyp, you can get [the url](https://plot.ly/~TestBot/7776/price-vs-carat/) for that example via 

http://ropensci.github.io/plotly-test-table/data/ef301b0e7c602b1cb1484f73426ac30dcbf24983/smooth-fill2.log

**Comment by cpsievert** [comment]
@chriddyp multiple traces will be generated if the colour/fill aesthetic is specified, but not for group. Do you want multiple traces so that we have more informative tooltips? I think that should be possible...I'm just using the default functionality for polygons (these are actually ribbons -- a special case of a polygon)

**Comment by tdhock** [comment]
for the interactivity it would be nice if the popup was only displayed for x-values with black dots, so then users could compare the observed data value with the mean data value.

that could be achieved if we evaluate the smooth line only on the grid of x-values that are present in the data set (rather than a uniformly spaced grid which I guess is what the code currently does).

**Comment by cpsievert** [comment]
Good idea @tdhock. Unfortunately I'm swamped with other stuff this week. This might have to wait until next week.

**Comment by chriddyp** [comment]
oh, nvm, when you guys were saying "basic polygon" I thought you meant Plotly's new basic polygon shapes (https://plot.ly/~etpinard/1647/plotly-shapes/).

This looks great to me! :dancer:

**Comment by cpsievert** [comment]
Great, I'm keen on merging this since it's such a big bug fix. We can work out the details of comparison mode in another pull request. Are you OK with that @tdhock?

**Comment by tdhock** [comment]
fine with me +1

**Pull request merged**
